version: '3.1'

services:
  uploader:
    container_name: uploader
    # user: 1000:1000
    image: golang:1.19.4
    restart: unless-stopped

    # limit cpu and memory
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    
    # mount a small tmpfs to /tmp for go cache
    tmpfs:
      - /tmp:rw,exec,mode=777,size=1g

    # go temp dir for go build cache
    environment:
      - GOTMPDIR=/tmp/
    
    
    volumes:
      - .:/streamupload
      - ./go:/go
      # - ~/go/bin:/go/bin
      # - ~/go/pkg:/go/pkg      
    ports:
      - 19090:19090
    working_dir: /streamupload
    # command: bash -c "echo started; while true; do sleep 3; done"
    command: ./streamupload
    
    